package com.mxz.supermarket.mapper;

import com.mxz.supermarket.model.Orderdetails;
import com.mxz.supermarket.model.OrderdetailsExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface OrderdetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbggenerated Thu Jan 16 12:42:42 CST 2020
     */
    int countByExample(OrderdetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbggenerated Thu Jan 16 12:42:42 CST 2020
     */
    int deleteByExample(OrderdetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbggenerated Thu Jan 16 12:42:42 CST 2020
     */
    int deleteByPrimaryKey(Integer detailsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbggenerated Thu Jan 16 12:42:42 CST 2020
     */
    int insert(Orderdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbggenerated Thu Jan 16 12:42:42 CST 2020
     */
    int insertSelective(Orderdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbggenerated Thu Jan 16 12:42:42 CST 2020
     */
    List<Orderdetails> selectByExample(OrderdetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbggenerated Thu Jan 16 12:42:42 CST 2020
     */
    Orderdetails selectByPrimaryKey(Integer detailsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbggenerated Thu Jan 16 12:42:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") Orderdetails record, @Param("example") OrderdetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbggenerated Thu Jan 16 12:42:42 CST 2020
     */
    int updateByExample(@Param("record") Orderdetails record, @Param("example") OrderdetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbggenerated Thu Jan 16 12:42:42 CST 2020
     */
    int updateByPrimaryKeySelective(Orderdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbggenerated Thu Jan 16 12:42:42 CST 2020
     */
    int updateByPrimaryKey(Orderdetails record);
}