package com.mxz.supermarket.mapper;

import com.mxz.supermarket.model.Purchasedetails;
import com.mxz.supermarket.model.PurchasedetailsExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PurchasedetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasedetails
     *
     * @mbggenerated Thu Jan 16 12:42:42 CST 2020
     */
    int countByExample(PurchasedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasedetails
     *
     * @mbggenerated Thu Jan 16 12:42:42 CST 2020
     */
    int deleteByExample(PurchasedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasedetails
     *
     * @mbggenerated Thu Jan 16 12:42:42 CST 2020
     */
    int deleteByPrimaryKey(Integer detailsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasedetails
     *
     * @mbggenerated Thu Jan 16 12:42:42 CST 2020
     */
    int insert(Purchasedetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasedetails
     *
     * @mbggenerated Thu Jan 16 12:42:42 CST 2020
     */
    int insertSelective(Purchasedetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasedetails
     *
     * @mbggenerated Thu Jan 16 12:42:42 CST 2020
     */
    List<Purchasedetails> selectByExample(PurchasedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasedetails
     *
     * @mbggenerated Thu Jan 16 12:42:42 CST 2020
     */
    Purchasedetails selectByPrimaryKey(Integer detailsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasedetails
     *
     * @mbggenerated Thu Jan 16 12:42:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") Purchasedetails record, @Param("example") PurchasedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasedetails
     *
     * @mbggenerated Thu Jan 16 12:42:42 CST 2020
     */
    int updateByExample(@Param("record") Purchasedetails record, @Param("example") PurchasedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasedetails
     *
     * @mbggenerated Thu Jan 16 12:42:42 CST 2020
     */
    int updateByPrimaryKeySelective(Purchasedetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasedetails
     *
     * @mbggenerated Thu Jan 16 12:42:42 CST 2020
     */
    int updateByPrimaryKey(Purchasedetails record);
}